### ISSUE TITLE
Add sbt version to build.properties

### ISSUE THREAD

**Issue by emilgoldsmith** [josepablocam/aquery#3]
Hi Jose!

I'm currently getting build errors, my sbt can't resolve the assembly plugin, I'm assuming it's because I have a newer version of SBT that probably has some other requirements since the project was developed a bit over a year ago, could we maybe add the sbt version to the `project/build.properties` file so my sbt automatically installs and uses the correct version (if that is the issue).

For reference this is the exact error (without the stack trace etc.): 

```
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.14.3: not found
```

Just let me know if you would rather do communication like this over e-mail instead of Github btw!

**Comment by josepablocam** [comment]
@emilgoldsmith Thanks for the issue! The latest commit 77454f3 fixes this. I put in the exact version I used (including minor version). Hope that helps. Github is great for this btw, having specific issues opened helps keep track of what I owe. Thanks

**Comment by emilgoldsmith** [comment]
Thanks! I hope it'll resolve my issues!
